### ISSUE TITLE
Select a design for the cupboard & others

### ISSUE THREAD

**Issue by vk047** [vk047/Chennai-parkour-collaboration#9]
## Todo:
Please add a list of Todos for your item.
- [ ] Google and find some ideas for the cupboard to be built
- [ ] Come with approximate measurements for the cupboard
- [ ] Fix a suitable place for the cupboard at the gym
